
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v11.5
      with:
        vcpkgJsonGlob: vcpkg.json

    - name: Configure CMake
      run: >
        cmake --preset "ninja_release_vcpkg"

    - name: Build
      run: cmake --build --preset "Ninja Release"
