
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install system dependencies
      if: matrix.os == 'ubuntu-24.04'
      run: |
        sudo apt-get update &&              \
        sudo apt-get install                \
            libomp-dev                      \
            nasm

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v11.5
      with:
        vcpkgJsonGlob: vcpkg.json

    - name: Add msbuild to PATH
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Configure CMake
      if: matrix.os == 'windows-latest'
      run: cmake --preset "release"

    - name: Configure CMake
      if: matrix.os == 'ubuntu-24.04'
      run: cmake --preset "release"
      env:
        CXX: clang++
        CC: clang

    - name: Build
      run: cmake --build --preset "build release"

    - name: Test
      run: ctest --preset "test release"
